### PR TITLE
Add itemsets and rate-limiting pages

### PR DESCRIPTION
**Pull request by Canisback**

### CODE REVIEW

**Review by thomasmarton — DISMISSED** [review]

**Comment by thomasmarton** [comment]
I'll approve the changes but I'm about to get the bugfix to yesterday's issue deployed so I'd like to keep the PR around so I can test it out with this one

**Comment by thomasmarton** [comment]
I'm actually going to have to ask for some changes. The markdown seems to be broken on a lot of places causing even github to be hella confused about them

**Comment by Canisback** [comment]
Updated rate-limiting with some details I didn't catch. Itemsets seems quite OK except for custom coloring that dooesn't appear on Github.

**Comment by thomasmarton** [comment]
I had some issues with the JSON escaper not handling the \ character properly, but after a quick fix, we're ready to have it in (I'll probably change the coloring of the document at some point tho)

**Review by thomasmarton — COMMENTED** [review]
Approved as is!

**Pull request merged**
